# Generated by Django 4.2.1 on 2023-05-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заказчик')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес заказчика')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='отдел')),
            ],
        ),
        migrations.CreateModel(
            name='LogReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='номер акта')),
                ('date', models.DateField(verbose_name='дата акта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('to_remove', models.BooleanField(default=False, verbose_name='удалить')),
                ('customer', models.ForeignKey(default='Бицерба РУС', null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ScaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='модель весов')),
                ('brand', models.CharField(default='Bizerba', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.CharField(blank=True, max_length=128, verbose_name='сервисный инженер')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('is_published', models.BooleanField(default=True, verbose_name='работает')),
                ('to_remove', models.BooleanField(default=False, verbose_name='уволить')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='запчасть')),
                ('vendor_code', models.CharField(max_length=16, verbose_name='артикул')),
                ('quantity', models.IntegerField(default=0, verbose_name='остаток')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='описание')),
                ('scale_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.scalemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=16, null=True, verbose_name='серийный номер')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer', verbose_name='заказчик')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.department', verbose_name='отдел')),
                ('scale_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.scalemodel', verbose_name='модель весов')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=16, verbose_name='артикул')),
                ('quantity', models.IntegerField(default=0, verbose_name='приход')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('to_remove', models.BooleanField(default=False, verbose_name='удалить')),
                ('act_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.logreceipt')),
                ('scale_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.scalemodel')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='заявка')),
                ('serial_number', models.CharField(max_length=16, null=True, verbose_name='серийный номер')),
                ('defect', models.TextField(blank=True, verbose_name='неисправность')),
                ('service_work', models.TextField(blank=True, verbose_name='выполненные работы')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('to_remove', models.BooleanField(default=False, verbose_name='удалить')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer', verbose_name='заказчик')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.serviceengineer', verbose_name='сервисный инженер')),
                ('scale_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.scalemodel', verbose_name='модель весов')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='установлено')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('to_remove', models.BooleanField(default=False, verbose_name='удалить')),
                ('number_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.jobapplication', verbose_name='заявка')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.sparepart', verbose_name='ЗИП')),
            ],
        ),
    ]
